# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\gzw10\Documents\workspace\test1\gacha_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import bangdreamgacha_numba
import random
import time

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        font = QtGui.QFont()
        font.setPointSize(14)
        MainWindow.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(MainWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.seed_layout = QtWidgets.QHBoxLayout()
        self.seed_layout.setObjectName("seed_layout")
        self.seed = QtWidgets.QLineEdit(MainWindow)
        self.seed.setObjectName("seed")
        self.seed_layout.addWidget(self.seed)
        self.random_seed_btn = QtWidgets.QPushButton(MainWindow)
        self.random_seed_btn.setObjectName("random_seed_btn")
        self.seed_layout.addWidget(self.random_seed_btn)
        self.gridLayout.addLayout(self.seed_layout, 5, 1, 1, 1)
        self.sims = QtWidgets.QLineEdit(MainWindow)
        self.sims.setObjectName("sims")
        self.gridLayout.addWidget(self.sims, 4, 1, 1, 1)
        self.label_total5 = QtWidgets.QLabel(MainWindow)
        self.label_total5.setObjectName("label_total5")
        self.gridLayout.addWidget(self.label_total5, 0, 0, 1, 1)
        self.want4 = QtWidgets.QSpinBox(MainWindow)
        self.want4.setMinimum(0)
        self.want4.setMaximum(50)
        self.want4.setProperty("value", 0)
        self.want4.setObjectName("want4")
        self.gridLayout.addWidget(self.want4, 2, 1, 1, 1)
        self.status = QtWidgets.QLabel(MainWindow)
        self.status.setObjectName("status")
        self.gridLayout.addWidget(self.status, 8, 0, 1, 2)
        self.want5 = QtWidgets.QSpinBox(MainWindow)
        self.want5.setMinimum(0)
        self.want5.setMaximum(50)
        self.want5.setProperty("value", 5)
        self.want5.setObjectName("want5")
        self.gridLayout.addWidget(self.want5, 1, 1, 1, 1)
        self.label_seed = QtWidgets.QLabel(MainWindow)
        self.label_seed.setObjectName("label_seed")
        self.gridLayout.addWidget(self.label_seed, 5, 0, 1, 1)
        self.label_sims = QtWidgets.QLabel(MainWindow)
        self.label_sims.setObjectName("label_sims")
        self.gridLayout.addWidget(self.label_sims, 4, 0, 1, 1)
        self.run_btn = QtWidgets.QPushButton(MainWindow)
        self.run_btn.setObjectName("run_btn")
        self.gridLayout.addWidget(self.run_btn, 6, 0, 1, 2)
        self.normal = QtWidgets.QCheckBox(MainWindow)
        self.normal.setChecked(False)
        self.normal.setObjectName("normal")
        self.gridLayout.addWidget(self.normal, 3, 0, 1, 2)
        self.label_want4 = QtWidgets.QLabel(MainWindow)
        self.label_want4.setObjectName("label_want4")
        self.gridLayout.addWidget(self.label_want4, 2, 0, 1, 1)
        self.label_want5 = QtWidgets.QLabel(MainWindow)
        self.label_want5.setObjectName("label_want5")
        self.gridLayout.addWidget(self.label_want5, 1, 0, 1, 1)
        self.total5 = QtWidgets.QSpinBox(MainWindow)
        self.total5.setMinimum(0)
        self.total5.setMaximum(50)
        self.total5.setProperty("value", 5)
        self.total5.setObjectName("total5")
        self.gridLayout.addWidget(self.total5, 0, 1, 1, 1)
        self.output = QtWidgets.QTextEdit(MainWindow)
        self.output.setReadOnly(True)
        self.output.setObjectName("output")
        self.gridLayout.addWidget(self.output, 7, 0, 1, 2)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Connect signals
        self.run_btn.clicked.connect(self.run_simulation)
        self.random_seed_btn.clicked.connect(self.random_seed)

    def random_seed(self):
        seed = random.randint(0, 2**31 - 1)
        self.seed.setText(str(seed))

    def run_simulation(self):
        try:
            total5 = self.total5.value()
            want5 = self.want5.value()
            want4 = self.want4.value()
            normal = 1 if self.normal.isChecked() else 0
            sims = int(self.sims.text())
            seed = int(self.seed.text())

            if want5 > total5:
                raise ValueError("想要5星不能超过总数")

            self.status.setText("模拟中...")
            self.output.clear()
            QtWidgets.QApplication.processEvents()  # 让界面更新

            start=time.time()
            arr = bangdreamgacha_numba.simulate_batch_numba(total5, want5, want4, normal, sims, seed)
            exp, med, p90, worst = bangdreamgacha_numba.summarize(arr)
            dur = time.time() - start

            result = f"""期望抽卡次数: {exp}
中位数抽卡次数: {med}
90%玩家在以下抽数内集齐: {p90}
非酋至多抽卡次数: {worst}
总耗时： {dur:.3f}秒"""
            self.output.setText(result)
            self.status.setText("完成")
        except Exception as e:
            self.output.setText(f"错误: {str(e)}")
            self.status.setText("错误")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "抽卡期望模拟器 - Numba GUI"))
        self.seed.setText(_translate("MainWindow", "123456789"))
        self.random_seed_btn.setText(_translate("MainWindow", "随机"))
        self.sims.setText(_translate("MainWindow", "10000000"))
        self.label_total5.setText(_translate("MainWindow", "当期5星总数"))
        self.status.setText(_translate("MainWindow", "就绪"))
        self.label_seed.setText(_translate("MainWindow", "随机种子"))
        self.label_sims.setText(_translate("MainWindow", "模拟次数"))
        self.run_btn.setText(_translate("MainWindow", "开始模拟"))
        self.normal.setText(_translate("MainWindow", "常驻池(含50保底)"))
        self.label_want4.setText(_translate("MainWindow", "想要4星数量"))
        self.label_want5.setText(_translate("MainWindow", "想要5星数量"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QWidget()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
